### PR TITLE
Added bearer auth class.

### PR DESCRIPTION
**Pull request by updatatoday**

### CODE REVIEW

**Comment by tomchristie** [comment]
Nice one, thanks!

Not made a decision on this just yet - possible that I'd defer to https://github.com/kennethreitz/requests/issues/4437 and follow their cue on this.

**Comment by CircleOnCircles** [comment]
This is not present in the docs. Shall I it to the docs?

**Comment by updatatoday** [comment]
It’s closed pr.

**Comment by florimondmanca** [comment]
Yup, this feature was not accepted. FYI you can now easily add your own authentication schemes using [custom auth](https://www.python-httpx.org/advanced/#customizing-authentication). :+1:

**Pull request closed without merging**
